kind: pipeline
name: default

steps:
- name: Run rspec
  image: ruby:2.6.0
  commands:
    - bundle
    - rspec
  when:
    event:
      - pull_request
- name: Bump and tag
  image: ruby:2.6.0
  environment:
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - gem install bump
    - git config --global user.name "  Kite Bot"
    - git config --global user.email "kite-bot@heliostech.fr"
    - git remote add authenticated-origin https://kite-bot:$GITHUB_API_KEY@github.com/${DRONE_REPO}
    - git fetch authenticated-origin
    - bump patch --commit-message 'Bump [ci skip]'
    - git tag $(cat VERSION)
    - git push authenticated-origin master
    - git push --tags authenticated-origin
  when:
    event: [push]
    branch: [master]
