app:
  name: "FeingKube"
  domain: "domain_REPLACE"
  subdomain: "subdomain_REPLACE"
ssl:
  enabled: true
  email: "support@example.com"
images:
  peatio: PEATIO:REPLACE
  barong: barong_image_REPLACE
  frontend: frontend_image_REPLACE_mikroapp:latest
  tower: tower_image_REPLACE
  postmaster: postmater_image_REPLACE
  arke: rubykube/arke:0.1.5
vendor:
  frontend: https://github.com/rubykube/mikroapp.git
storage:
  provider: "storage_provider_SED_IN_DEPLOYMENT_FOR_REPLACING"
  bucketName: "storage_bucket_name_SED_IN_DEPLOYMENT_FOR_REPLACING"
  accessKey: "storage_api_key_SED_IN_DEPLOYMENT_FOR_REPLACING"
  secretKey: "storage_secret_key_SED_IN_DEPLOYMENT_FOR_REPLACING"
terraform:
  credentials: "~/safe/microkube.json"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+15005550000"
  account_sid: "twilio-account_sid-changeme"
  auth_token: "twilio-auth_token-changeme"
sendgrid_api_key: "sendgrid_api_key_SED_IN_DEPLOYMENT_FOR_REPLACING"
arke:
  strategy:
    type: 'copy'
    pair: 'BTCUSD'
    target:
      driver: rubykube
      market: 'BTCUSD'
      host: 'http://peatio:8000'
      name: arke@arke.io
      key: f351baf4291993b4
      secret: 2a224f4660ff697bad88c84831a5a3fa
    sources:
      - driver: binance
        market: 'BTCUSDT'
        host: "api.binance.com"
        name: binance.com@info.soc
        key: arke-source-binance-key-changeme
        secret: arke-source-binance-secret-changeme
